import {
	ListingStatus,
	TransferType,
	type ListingPreviewDto,
} from '@shared/api/generated/listings-api';

const items: ListingPreviewDto[] = [
	{
		id: 'mock-1',
		title: 'Учебник по математике',
		status: ListingStatus.Completed,
		city: 'Москва',
		thumbnailUrl: 'https://placehold.co/600x400?text=Ad+1',
		category: { id: 'cat-1', name: 'Книги' },
		createdAt: '2026-04-01T10:00:00Z',
		transferType: TransferType.Charity,
		condition: '',
		viewCount: 42,
		weightGrams: 42,
		co2SavedG: 42,
		wasteSavedG: 42,
	},
	{
		id: 'mock-2',
		title: 'Ноутбук для учебы',
		status: ListingStatus.Completed,
		city: 'Санкт-Петербург',
		thumbnailUrl: 'https://placehold.co/600x400?text=Ad+2',
		category: { id: 'cat-2', name: 'Техника' },
		createdAt: '2026-04-02T10:00:00Z',
		transferType: TransferType.Exchange,
		condition: '',
		viewCount: 42,
		weightGrams: 42,
		co2SavedG: 42,
		wasteSavedG: 42,
	},
	{
		id: 'mock-3',
		title: 'Настольная лампа',
		status: ListingStatus.Completed,
		city: 'Казань',
		thumbnailUrl: 'https://placehold.co/600x400?text=Ad+3',
		category: { id: 'cat-3', name: 'Дом' },
		createdAt: '2026-04-03T10:00:00Z',
		transferType: TransferType.Gift,
		condition: '',
		viewCount: 42,
		weightGrams: 42,
		co2SavedG: 42,
		wasteSavedG: 42,
	},
	{
		id: 'mock-4',
		title: 'Гитара акустическая',
		status: ListingStatus.Completed,
		city: 'Екатеринбург',
		thumbnailUrl: 'https://placehold.co/600x400?text=Ad+4',
		category: { id: 'cat-4', name: 'Музыка' },
		createdAt: '2026-04-04T10:00:00Z',
		transferType: TransferType.Charity,
		condition: '',
		viewCount: 42,
		weightGrams: 42,
		co2SavedG: 42,
		wasteSavedG: 42,
	},
	{
		id: 'mock-5',
		title: 'Кресло офисное',
		status: ListingStatus.Completed,
		city: 'Новосибирск',
		thumbnailUrl: 'https://placehold.co/600x400?text=Ad+5',
		category: { id: 'cat-5', name: 'Мебель' },
		createdAt: '2026-04-05T10:00:00Z',
		transferType: TransferType.Exchange,
		condition: '',
		viewCount: 42,
		weightGrams: 42,
		co2SavedG: 42,
		wasteSavedG: 42,
	},
	{
		id: 'mock-6',
		title: 'Рюкзак городской',
		status: ListingStatus.Completed,
		city: 'Самара',
		thumbnailUrl: 'https://placehold.co/600x400?text=Ad+6',
		category: { id: 'cat-6', name: 'Аксессуары' },
		createdAt: '2026-04-06T10:00:00Z',
		transferType: TransferType.Gift,
		condition: '',
		viewCount: 42,
		weightGrams: 42,
		co2SavedG: 42,
		wasteSavedG: 42,
	},
	{
		id: 'mock-7',
		title: 'Велосипед',
		status: ListingStatus.Completed,
		city: 'Краснодар',
		thumbnailUrl: 'https://placehold.co/600x400?text=Ad+7',
		category: { id: 'cat-7', name: 'Спорт' },
		createdAt: '2026-04-07T10:00:00Z',
		transferType: TransferType.Charity,
		condition: '',
		viewCount: 42,
		weightGrams: 42,
		co2SavedG: 42,
		wasteSavedG: 42,
	},
	{
		id: 'mock-8',
		title: 'Куртка демисезонная',
		status: ListingStatus.Completed,
		city: 'Нижний Новгород',
		thumbnailUrl: 'https://placehold.co/600x400?text=Ad+8',
		category: { id: 'cat-8', name: 'Одежда' },
		createdAt: '2026-04-08T10:00:00Z',
		transferType: TransferType.Exchange,
		condition: '',
		viewCount: 42,
		weightGrams: 42,
		co2SavedG: 42,
		wasteSavedG: 42,
	},
	{
		id: 'mock-9',
		title: 'Наушники',
		status: ListingStatus.Completed,
		city: 'Ростов-на-Дону',
		thumbnailUrl: 'https://placehold.co/600x400?text=Ad+9',
		category: { id: 'cat-9', name: 'Электроника' },
		createdAt: '2026-04-09T10:00:00Z',
		transferType: TransferType.Gift,
		condition: '',
		viewCount: 42,
		weightGrams: 42,
		co2SavedG: 42,
		wasteSavedG: 42,
	},
];

export { items };
